---

- name: Repository key (Debian)
  apt_key:
    state=present
    url="{{nodejs_repository_key}}"
  
- name: NodeJS Repository (Debian)
  apt_repository:
    state=present
    repo="deb {{nodejs_repository}} {{ansible_distribution_release}} main"
    update_cache=yes

- name: Install NodeJS (Debian)
  apt:
    name=nodejs
    state=present

# vi:ts=2:sw=2:et:ft=yaml
