---

- include: install/Debian.yml
  when: ansible_os_family == 'Debian'
  
- include: install/RedHat.yml
  when: ansible_os_family == 'RedHat'
 
- name: Currently installed version
  command: npm --version
  register: n_version

- name: Upgrade npm version
  npm:
    name=npm
    global=yes
    version="{{nodejs_version}}"
  when: n_version.stdout != nodejs_version
 
# vi:ts=2:sw=2:et:ft=yaml
