---
#
# 
#

- name: Install NodeJS
  apt:
    name=nodejs
    state=present
  sudo: yes

- name: Currently installed version
  command: npm --version
  register: n_version

- name: Upgrade npm version
  npm:
    name=npm
    global=yes
    version="{{node_version}}"
  when: n_version.stdout != node_version
 
# vi:ts=2:sw=2:et:ft=yaml
